export const FLEX_CORE_ABI = [
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        indexed: false,
        name: "loan_info",
        type: "tuple",
      },
    ],
    name: "LoanProposed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      { indexed: false, name: "user_custom_id", type: "string" },
      {
        indexed: false,
        name: "renegotiaited_loan_id",
        type: "bytes32",
      },
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        indexed: false,
        name: "renegotiaited_loan_info",
        type: "tuple",
      },
    ],
    name: "LoanRenegotiated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        indexed: false,
        name: "loan_info",
        type: "tuple",
      },
    ],
    name: "LoanTermsChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      { indexed: false, name: "user_custom_id", type: "string" },
      {
        indexed: false,
        name: "renegotiaited_loan_id",
        type: "bytes32",
      },
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        indexed: false,
        name: "renegotiaited_loan_info",
        type: "tuple",
      },
    ],
    name: "RenegotiationTermsChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        indexed: false,
        name: "loan",
        type: "tuple",
      },
    ],
    name: "LoanAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      { indexed: false, name: "user_custom_id", type: "string" },
      {
        indexed: false,
        name: "renegotiaited_loan_id",
        type: "bytes32",
      },
      { indexed: false, name: "messageURI", type: "string" },
      { indexed: false, name: "lender_or_borrower", type: "uint256" },
      { indexed: false, name: "chat_id", type: "uint256" },
    ],
    name: "ChatPushed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      { indexed: false, name: "user_custom_id", type: "string" },
      {
        indexed: false,
        name: "renegotiaited_loan_id",
        type: "bytes32",
      },
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        indexed: false,
        name: "renegotiaited_loan_info",
        type: "tuple",
      },
    ],
    name: "LoanReNegotiationAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      { indexed: false, name: "proposer_type", type: "bytes32" },
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        indexed: false,
        name: "proposal_details",
        type: "tuple",
      },
      { indexed: false, name: "existence", type: "bool" },
    ],
    name: "ProposalPushed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      { indexed: false, name: "proposal_accepted", type: "bytes32" },
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        indexed: false,
        name: "proposal_details",
        type: "tuple",
      },
      { indexed: false, name: "existence", type: "bool" },
    ],
    name: "ProposalAccepted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        indexed: false,
        name: "loan_details",
        type: "tuple",
      },
    ],
    name: "LoanRepaid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        indexed: false,
        name: "loan_details",
        type: "tuple",
      },
    ],
    name: "LoanLiquidated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      { indexed: false, name: "buyer", type: "address" },
      { indexed: false, name: "buyout_amount", type: "uint256" },
      { indexed: false, name: "existence", type: "bool" },
    ],
    name: "BuyoutProposed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      { indexed: false, name: "buyer", type: "address" },
      { indexed: false, name: "buyout_amount", type: "uint256" },
      { indexed: false, name: "existence", type: "bool" },
    ],
    name: "BuyOutCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      { indexed: false, name: "buyer", type: "address" },
      { indexed: false, name: "buyout_amount", type: "uint256" },
      { indexed: false, name: "existence", type: "bool" },
    ],
    name: "LoanBought",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, name: "loan_id", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "CollateralTopUp",
    type: "event",
  },
  {
    inputs: [{ name: "_flex_calc", type: "address" }],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      { name: "_margin_cutoff", type: "uint256" },
      { name: "_collateral_ratio", type: "uint256" },
      { name: "_fixed_intererst_rate", type: "uint256" },
      { name: "_borrow_amount", type: "uint256" },
      { name: "_time_limit", type: "bool" },
      { name: "_time_amount", type: "uint256" },
      { name: "_collateral_type", type: "address" },
      { name: "_principal_type", type: "address" },
      { name: "_access_control", type: "bool" },
      { name: "_recipient", type: "address" },
      { name: "_loan_type", type: "uint256" },
      { name: "_collateral_deposit", type: "uint256" },
    ],
    name: "propose_loan",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { name: "_loan_id", type: "uint256" },
      { name: "_user_custom_id", type: "string" },
      { name: "_margin_cutoff", type: "uint256" },
      { name: "_collateral_ratio", type: "uint256" },
      { name: "_fixed_intererst_rate", type: "uint256" },
      { name: "_time_amount", type: "uint256" },
    ],
    name: "renegotiate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_loan_id", type: "uint256" },
      { name: "_user_custom_id", type: "string" },
      { name: "_margin_cutoff", type: "uint256" },
      { name: "_collateral_ratio", type: "uint256" },
      { name: "_fixed_intererst_rate", type: "uint256" },
      { name: "_time_amount", type: "uint256" },
    ],
    name: "change_renegotiation_terms",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_loan_id", type: "uint256" },
      { name: "_margin_cutoff", type: "uint256" },
      { name: "_collateral_ratio", type: "uint256" },
      { name: "_fixed_intererst_rate", type: "uint256" },
      { name: "_time_amount", type: "uint256" },
    ],
    name: "change_original_loan_terms",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_loan_id", type: "uint256" },
      { name: "_user_custom_id", type: "string" },
    ],
    name: "accept_renegotiation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_loan_id", type: "uint256" },
      { name: "_user_custom_id", type: "string" },
      { name: "message", type: "string" },
    ],
    name: "push_renegotiation_chat",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_loan_id", type: "uint256" },
      { name: "_erc20Amount", type: "uint256" },
    ],
    name: "accept_loan_terms",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { name: "_loan_id", type: "uint256" },
      { name: "_margin_cutoff", type: "uint256" },
      { name: "_fixed_intererst_rate", type: "uint256" },
      { name: "_time_amount", type: "uint256" },
    ],
    name: "propose_new_terms_after_acceptance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_loan_id", type: "uint256" }],
    name: "accept_new_proposal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "_loan_id", type: "uint256" }],
    name: "repay_loan",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ name: "_loan_id", type: "uint256" }],
    name: "liquidate_loan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_loan_id", type: "uint256" },
      { name: "_buyout_amount", type: "uint256" },
    ],
    name: "propose_loan_buyout",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ name: "_loan_id", type: "uint256" }],
    name: "cancel_loan_buyout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "_loan_id", type: "uint256" },
      { name: "_buyer", type: "address" },
    ],
    name: "accept_loan_buyout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "loan_id", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    name: "top_up_collateral",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ name: "token_address", type: "address" }],
    name: "add_token_support",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "asset", type: "address" },
      { name: "price_feed_address", type: "address" },
    ],
    name: "add_price_feed_address",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "loan_id", type: "uint256" }],
    name: "get_loan_Details_by_id",
    outputs: [
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "loan_id", type: "uint256" },
      { name: "user_custom_id", type: "string" },
    ],
    name: "get_renegotiated_loan_by_its_id",
    outputs: [
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "loan_id", type: "uint256" }],
    name: "calulate_required_loan_principal_or_collateral_for_acceptance",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "loan_id", type: "uint256" },
      { name: "user_custom_id", type: "string" },
    ],
    name: "calulate_require_loan_principal_or_collateral_for_renegotiation_acceptance",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "loan_id", type: "uint256" }],
    name: "get_margin_cutoff_in_collateral",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "loan_id", type: "uint256" }],
    name: "get_health_status",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "get_block_time_stamp",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  { stateMutability: "payable", type: "fallback" },
  {
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "flex_calc",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "chat_count",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "loan_counter",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lender_loan",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "borrower_loan",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proposed",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "accepted",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fulfilled",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "borrower_proposal",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lender_proposal",
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "loan_details",
    outputs: [
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "loan_timers",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "uint256" }],
    name: "loan_existence_tracker",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "arg0", type: "uint256" },
      { name: "arg1", type: "bytes32" },
    ],
    name: "loan_renegotiations",
    outputs: [
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "arg0", type: "uint256" },
      { name: "arg1", type: "bytes32" },
    ],
    name: "loan_renegotiation_id_tracker",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "arg0", type: "uint256" },
      { name: "arg1", type: "bytes32" },
    ],
    name: "loan_proposals",
    outputs: [
      {
        components: [
          { name: "borrower", type: "address" },
          { name: "lender", type: "address" },
          { name: "margin_cutoff", type: "uint256" },
          { name: "collateral_ratio", type: "uint256" },
          { name: "fixed_interest_rate", type: "uint256" },
          { name: "borrow_amount", type: "uint256" },
          { name: "time_limit", type: "bool" },
          { name: "time_amount", type: "uint256" },
          { name: "collateral_type", type: "address" },
          { name: "collateral_deposited", type: "uint256" },
          { name: "principal_type", type: "address" },
          { name: "current_debt", type: "uint256" },
          { name: "access_control", type: "bool" },
          { name: "state", type: "bytes32" },
          { name: "loan_type", type: "uint256" },
        ],
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "arg0", type: "uint256" },
      { name: "arg1", type: "bytes32" },
    ],
    name: "loan_proposal_tracker",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "address" }],
    name: "supported_assets",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "address" }],
    name: "supported_assets_pricefeed",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "address" }],
    name: "price_feeds",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "arg0", type: "uint256" },
      { name: "arg1", type: "address" },
    ],
    name: "loan_buyouts",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
];

export const ERC20_ABI = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "sender", type: "address" },
      { indexed: true, name: "receiver", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "owner", type: "address" },
      { indexed: true, name: "spender", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
    name: "Approval",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, name: "withdrawer", type: "address" },
      { indexed: true, name: "receiver", type: "address" },
      { indexed: true, name: "owner", type: "address" },
      { indexed: false, name: "assets", type: "uint256" },
      { indexed: false, name: "shares", type: "uint256" },
    ],
    name: "Withdraw",
    type: "event",
  },
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    inputs: [],
    name: "name",
    outputs: [{ name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ name: "", type: "uint8" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { name: "receiver", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "transfer",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "sender", type: "address" },
      { name: "receiver", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "transferFrom",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "arg0", type: "address" }],
    name: "balanceOf",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { name: "arg0", type: "address" },
      { name: "arg1", type: "address" },
    ],
    name: "allowance",
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
];
